# Generated by Django 5.0.4 on 2024-05-08 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='Generic Area', max_length=32)),
                ('description', models.CharField(default='Generic Activities', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(default='Generic Goal', max_length=64)),
                ('description', models.CharField(default='Generic Goal description', max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('days_duration', models.IntegerField(default=7)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8)),
                ('state', models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=8)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrantGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ggname', models.CharField(default='Generic Grant Goal', max_length=64)),
                ('description', models.CharField(default='Generic Grant Goal description', max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('days_duration', models.IntegerField(default=7)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8)),
                ('state', models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuename', models.CharField(default='Generic Issue', max_length=64)),
                ('description', models.CharField(default='Generic Issue description', max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('days_duration', models.IntegerField(default=7)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8)),
                ('state', models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=8)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubGrantGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sggname', models.CharField(default='Generic Sub Grant Goal', max_length=64)),
                ('description', models.CharField(default='Generic Sub Grant Goal description', max_length=128)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('days_duration', models.IntegerField(default=7)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('HEIGHT', 'HG'), ('MIDDLE', 'MD'), ('LOW', 'LW')], max_length=8)),
                ('state', models.CharField(choices=[('NOT STARTED', 'NS'), ('DOING', 'DG'), ('DONE', 'DN')], max_length=16)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=8)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
