# Generated by Django 5.0.6 on 2024-05-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='subgrantgoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subgrantgoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgrantgoal',
            name='grantgoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.grantgoal'),
            preserve_default=False,
        ),
    ]
